version: '3.8'

services:
  kafka:
    image: ${KAFKA_IMAGE}
    hostname: kafka
    container_name: kafka
    ports:
      - "${KAFKA_EXTERNAL_PORT}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_QUORUM_PORT}

      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - ${KAFKA_VOLUME_NAME}:/var/lib/kafka/data

  redis:
    image: redis/redis-stack-server:${REDIS_IMAGE_TAG}
    hostname: redis
    container_name: redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
      - "${REDIS_INSIGHT_EXTERNAL_PORT}:8001"
    environment:
      REDIS_ARGS: "--appendonly yes"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    hostname: api
    container_name: slice-stream-engine-api
    ports:
      - "${API_EXTERNAL_PORT}:8080"
    environment:
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - kafka
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    hostname: client
    container_name: slice-stream-engine-client
    ports:
      - "${CLIENT_EXTERNAL_PORT}:5173" # Map host port 3000 to container port 5173 (Vite default)
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL} # This might need to be 'http://api:8080' if client calls API within docker network
    depends_on:
      - api

volumes:
  ${KAFKA_VOLUME_NAME}:
